select
    bars.market_bar_key,
    {{ surrogate_key(['bars.symbol', 'bars.currency']) }} as asset_key,
    {{ surrogate_key(['bars.provider']) }} as provider_key,
    bars.bar_start::date as date_key,
    bars.provider,
    bars.symbol,
    bars.currency,
    bars.interval,
    bars.bar_start,
    bars.bar_end,
    bars.open,
    bars.high,
    bars.low,
    bars.close,
    bars.volume,
    bars.trade_count,
    bars.vwap,
    bars.simple_return,
    bars.log_return,
    bars.loaded_at
from {{ ref('int_market_returns') }} as bars
